measurements:
  - name: cluster1
    cluster:
        host: cluster1-node1.example.com
        port: 9000
    iperf:
      type: udp
      time: 10
      bandwidth: 800000
      size: 100
      report-interval: 1
      enhanced-output: false
      connection:
        host: localhost
        port: 5000