measurements:
  - name: local-measurement
    cluster:
        type: local
        host: cluster1-node1.example.com
    client:
        address: "127.0.0.1:5000"
    turncat:
      log: "all:INFO"
      #client-address: "udp://127.0.0.1:5000"
      turn-server-address: "k8s://stunner/udp-gateway:udp-listener"
      peer-host-address: "udp://$(kubectl get svc iperf-server -o jsonpath=\"{.spec.clusterIP}\"):5001"
    iperf:
      type: udp
      time: 10
      bandwidth: 800000
      size: 100
      report-interval: 1
      enhanced-output: false